FROM ruby:3.4.10

# 必要なライブラリをインストール
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev postgresql-client libyaml-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 先にGemfileだけコピーしてbundle install(ビルドを速くするため)
COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000
CMD ["bin/rails", "server", "-b", "0.0.0.0"]